# Generated by Django 5.2.5 on 2026-03-01 06:27

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_goals', '0002_savingsgoal_icon_savingsgoal_monthly_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='monthly_contribution',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=12),
        ),
    ]
