# Generated by Django 5.2.5 on 2026-01-22 19:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_wallet_wallettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code (e.g., USD, EUR, INR)', max_length=3),
        ),
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Overall financial health score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spending_discipline_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('savings_ratio_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('credit_utilization_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('loan_burden_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('risk_exposure_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateField(help_text='Month this score represents')),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation of score and changes')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Actionable recommendations for improvement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Health Score',
                'verbose_name_plural': 'Financial Health Scores',
                'db_table': 'financial_health_scores',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ScoreFactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(choices=[('spending_discipline', 'Spending Discipline'), ('savings_ratio', 'Savings Ratio'), ('credit_utilization', 'Credit Utilization'), ('loan_burden', 'Loan Burden'), ('risk_exposure', 'Risk Exposure')], max_length=50)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('weight', models.FloatField(default=0.2, help_text='Weight of this factor (default: 0.2 = 20%)')),
                ('metrics', models.JSONField(default=dict, help_text='Raw metrics used to calculate this factor score')),
                ('explanation', models.TextField(help_text='Explanation of how this factor score was calculated')),
                ('health_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_details', to='ai_assistant.financialhealthscore')),
            ],
            options={
                'verbose_name': 'Score Factor Detail',
                'verbose_name_plural': 'Score Factor Details',
                'db_table': 'score_factor_details',
            },
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['user', '-month'], name='financial_h_user_id_8a9f06_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['-calculation_date'], name='financial_h_calcula_01053c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialhealthscore',
            unique_together={('user', 'month')},
        ),
    ]
