# Generated by Django 5.2.5 on 2026-01-25 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_data', models.JSONField(default=dict, help_text='Full JSON output from AI analysis (patterns, anomalies, recommendations)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['user', '-analysis_date'], name='ai_assistan_user_id_8b1d6c_idx')],
            },
        ),
    ]
