# Generated by Django 5.2.5 on 2026-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_spendingpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mongo_doc_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
