# Generated by Django 5.2.5 on 2026-03-01 06:27

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_document_mongo_doc_id_document_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=core.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=core.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='recommendations',
            field=core.encryption.EncryptedJSONField(blank=True, default=list, help_text='Actionable recommendations for improvement (encrypted)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_emi',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scorefactordetail',
            name='metrics',
            field=core.encryption.EncryptedJSONField(blank=True, default=dict, help_text='Raw metrics used to calculate this factor score (encrypted)'),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='analysis_data',
            field=core.encryption.EncryptedJSONField(blank=True, default=dict, help_text='Full JSON output from AI analysis (patterns, anomalies, recommendations) (encrypted)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, help_text='Current wallet balance (encrypted)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, help_text='Transaction amount (encrypted)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Transaction description or notes (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='metadata',
            field=core.encryption.EncryptedJSONField(blank=True, default=dict, help_text='Additional transaction metadata (encrypted)'),
        ),
    ]
