# Generated by Django 5.2.5 on 2026-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pdf', 'PDF Upload')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_document',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
