# Generated by Django 5.2.5 on 2026-03-01 06:27

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_source_transaction_source_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=core.encryption.EncryptedTextField(blank=True, default=''),
        ),
    ]
