# Generated by Django 5.2.5 on 2026-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_credits_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('goal', 'Goal'), ('transaction', 'Transaction'), ('wallet', 'Wallet'), ('system', 'System')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
