# Generated by Django 5.2.5 on 2026-02-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4)),
                ('card_holder', models.CharField(max_length=100)),
                ('expiry', models.CharField(help_text='MM/YY', max_length=5)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard')], default='Visa', max_length=12)),
                ('gradient_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
