# Generated by Django 5.2.5 on 2026-03-01 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=5)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil')], default='en', max_length=5)),
                ('dark_mode', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('goal_reminders', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('ai_insights', models.BooleanField(default=False)),
                ('market_updates', models.BooleanField(default=False)),
                ('show_balance', models.BooleanField(default=True)),
                ('analytics_sharing', models.BooleanField(default=False)),
                ('crash_reports', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
