# Generated by Django 5.2.5 on 2026-03-01 06:27

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, max_digits=12),
        ),
    ]
